### ISSUE TITLE
Running mediapipe-rs on browser

### ISSUE THREAD

**Issue by nmgray** [WasmEdge/mediapipe-rs#13]
Is it possible to run mediapipe-rs in the browser? The following code compiles using web-pack, however when attempting to load the model an unreachable runtime error is produced. Is this a wasm environment issue or is it not possible to run this in the browser?

```
use image::{DynamicImage, ImageBuffer, Rgba};
use mediapipe_rs::postprocess::utils::DrawLandmarksOptions;
use mediapipe_rs::tasks::vision::FaceLandmarkConnections;
use mediapipe_rs::tasks::vision::FaceLandmarkerBuilder;
use wasm_bindgen::prelude::*;
use wasm_bindgen::Clamped;
use web_sys::ImageData;

static MODEL_BUFFER: &[u8] = include_bytes!("../face_landmarker.task");

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

#[wasm_bindgen]
pub fn process_image_data(data: Clamped<Vec<u8>>, width: u32, height: u32) -> ImageData {
    let model = MODEL_BUFFER.to_vec();
    // Create a dynamic img buffer
    let img_buffer: ImageBuffer<Rgba<u8>, Vec<u8>> =
        ImageBuffer::from_vec(width, height, data.clone().0).unwrap();
    let mut dynamic_image = DynamicImage::ImageRgba8(img_buffer);
    let face_landmark_results = FaceLandmarkerBuilder::new()
        .num_faces(1) // set max number of faces to detect
        .min_face_detection_confidence(0.5)
        .min_face_presence_confidence(0.5)
        .min_tracking_confidence(0.5)
        .output_face_blendshapes(true)
        .build_from_buffer(model)
        .unwrap_or_else(|err| {
            log(&format!("Error: {:?}", err));
            panic!("Failed to build face landmarker");
        });
    let img = dynamic_image.to_rgba8().clone().into_raw();
    // Create a new ImageData object
    let data_slice: Clamped<&[u8]> = Clamped(img.as_slice());

    ImageData::new_with_u8_clamped_array_and_sh(data_slice, width, height).unwrap()
}

```

It is built with webpack:

`wasm-pack build --target web`

I am serving it with:

`npx serve`

More details are probably needed but I would like to know if there are inherent resource limitations that prevent this from running in the browser.

**Comment by hydai** [comment]
This project relies on the wasi-nn proposal. It cannot be executed if the environment doesn't provide it.
https://github.com/WasmEdge/mediapipe-rs/blob/main/Cargo.toml#L30

**Comment by nmgray** [comment]
That makes sense. Since the library is not available in the browser, it accesses an unreachable code segment. Any suggestions on providing the wasi-nn resources in the browser, or is this not an appropriate use-case for the mediapipe-rs project?

Thanks for the help.

**Comment by hydai** [comment]
WASI-NN is a WIP WASI proposal, so I don't think any browser is going to implement it at the current moment. If you really want to use it, maybe you can use TensorFlowJS or something to implement similar functions and export these functions to Wasm to make it support WASI-NN.

**Comment by nmgray** [comment]
That seems like a large task. Might be neat to try to implement though. Thanks for the help.
