### ISSUE TITLE
Targets other than `wasm32-wasi`

### ISSUE THREAD

**Issue by 9oelM** [WasmEdge/mediapipe-rs#3]
I see that the only target available is `wasm32-wasi`. but would it be also possible to build for `aarch64-unknown-linux-gnu`, for example? And if not, what would be the reason for that?

**Comment by 9oelM** [comment]
Well I guess one problem is `wasi-nn-0.4.0`
```
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasi-nn-0.4.0/src/graph.rs:391:9:
not implemented: this crate is only intended to be used with `--target=wasm32-wasi`
```

**Comment by hydai** [comment]
WASI-NN only supports the `wasm32-wasi` backend. Unless an alternative crate replaces it, there is no way to support another backend.

**Comment by 9oelM** [comment]
Thanks for the answer 👍
