### ISSUE TITLE
Audio Example Not Running while using FFmpeg 

### ISSUE THREAD

**Issue by Hrushi20** [WasmEdge/mediapipe-rs#5]
<img width="1352" alt="Screenshot 2023-12-14 at 3 51 32 PM" src="https://github.com/WasmEdge/mediapipe-rs/assets/65367566/1dd3db65-987e-49cf-8565-96fed4729529">

I'm using Mac M1 hardware. I used the below command to build WasmEdge 

```console
$  cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DWASMEDGE_BUILD_AOT_RUNTIME=OFF -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="TensorflowLite" -DWASMEDGE_BUILD_TOOLS=OFF ..
```

I ran the below commands as well -
```console
$ export WASI_SDK=/opt/wasi-sdk
$ export BINDGEN_EXTRA_CLANG_ARGS="--sysroot=/opt/wasi-sdk/share/wasi-sysroot --target=wasm32-wasi -fvisibility=default"

```

I'm trying to run the audio model using FFmpeg. I'm trying to compare the results of the current implementation and [WasmEdge FFmpeg-Rust](https://github.com/Hrushi20/rust-ffmpeg) crate implementation and also observe the performance gain.

**Comment by Hrushi20** [comment]
<img width="864" alt="Screenshot 2023-12-14 at 7 17 35 PM" src="https://github.com/WasmEdge/mediapipe-rs/assets/65367566/508db872-5eb5-4b60-9eaa-0622ad7e763f">

I get the above issue while compiling with ffmpeg in mediapipe-rs

**Comment by yanghaku** [comment]
Hello @Hrushi20 , can you show your compile command with `cargo`?

**Comment by Hrushi20** [comment]
``` console
$ cargo run --release --example audio_classification -- ./assets/models/audio_classification/yamnet_audio_classifier_with_metadata.tflite ./assets/testdata/audio/speech_16000_hz_mono.wav
```
The above is my cargo compile command

**Comment by yanghaku** [comment]
Do you set the environment `WASI_SDK` and `BINDGEN_EXTRA_CLANG_ARGS` before run `cargo`?The function `clock` is in `libwasi-emulated-process-clocks.a`,

**Comment by Hrushi20** [comment]
> Do you set the environment `WASI_SDK` and `BINDGEN_EXTRA_CLANG_ARGS` before run `cargo`?The function `clock` is in `libwasi-emulated-process-clocks.a`.
> 
> You should set the feature `ffmpeg`, (add args for cargo: `--features="ffmpeg"`). And the `build.rs` will link with ffmpeg library and `libwasi-emulated-process-clocks.a`

Yes I did set the `WASI_SDK` and `BINDGEN_EXTRA_CLANG_ARGS` before running cargo based on the README.

I am not sure about `export FFMPEG_DIR`. I set it to `/usr/local/lib` because the prebuilt wasi is not for macos ig.

**Comment by Hrushi20** [comment]
The MacOs uses arm chip. Are the FFmpeg dependencies for `x86` processor?

**Comment by yanghaku** [comment]
> I'm using MacOs M1 (Arm) chip. Are the FFmpeg dependencies for `x86` processor?

The ```FFMPEG_DIR``` is necessary, And FFmpeg library is ```wasm32-wasi``` target (not arm, not x86), you can download from [here](https://github.com/yanghaku/ffmpeg-wasm32-wasi/releases/)

And the feature ```ffmpeg``` is not enabled by default,  you can add the ```--features="ffmpeg"``` when built using `cargo`.

**Comment by Hrushi20** [comment]
<img width="1353" alt="Screenshot 2023-12-14 at 8 20 23 PM" src="https://github.com/WasmEdge/mediapipe-rs/assets/65367566/3c68e323-13e3-4aef-b88d-88d1c7578de2">

I get the same error.

**Comment by Hrushi20** [comment]
Does FFmpeg and Symphonia gives different results while processing audio? I am not able to run FFmpeg on my system using README, however while processing Audio using [WasmEdge Rust FFmpeg SDK](https://github.com/WasmEdge/mediapipe-rs/pull/4), I get different results.

**Comment by yanghaku** [comment]
1. The error message ```library kind `framework` is only supported on Apple targets``` may be bindgen error when parsing FFmpeg header files to generate rust code in MacOS.
[audio_classification_wasm.zip](https://github.com/WasmEdge/mediapipe-rs/files/13682391/audio_classification_wasm.zip)

2. The FFmpeg and Symphonia give the same results.

**Comment by Hrushi20** [comment]
Hey! I cloned the FFmpeg Wasm Repo, compiled and imported it locally on my machine. It is working as expected. 

Also, I verified that FFmpeg and Symphonia gives the same Results 😄.

 Thanks for your time.
