### ISSUE TITLE
error: could not compile `mediapipe-rs`

### ISSUE THREAD

**Issue by aqq777** [WasmEdge/mediapipe-rs#6]
rust version: rustc 1.77.1 (7cf61ebde 2024-03-27)
rustup default :stable-x86_64-unknown-linux-gnu (default)
wasmedge version 0.13.5
OS: ubuntu 22.04

After cloning the code from github,  I run the command as follow:
`cargo run --release --example image_classification -- ./assets/models/image_classification/efficientnet_lite0_fp32.tflite ./assets/testdata/img/burger.jpg`

then I got such message, how to fix these errros?

<pre><font color="#26A269"><b> Updating</b></font> crates.io index
<font color="#26A269"><b>    Updating</b></font> git repository `https://github.com/yanghaku/rust-ffmpeg.git`
<font color="#26A269"><b>  Downloaded</b></font> extended v0.1.0
<font color="#26A269"><b>  Downloaded</b></font> symphonia v0.5.4
<font color="#26A269"><b>  Downloaded</b></font> symphonia-format-riff v0.5.4
<font color="#26A269"><b>  Downloaded</b></font> symphonia-codec-pcm v0.5.4
<font color="#26A269"><b>  Downloaded</b></font> symphonia-metadata v0.5.4
<font color="#26A269"><b>  Downloaded</b></font> encoding_rs v0.8.33
<font color="#26A269"><b>  Downloaded</b></font> 6 crates (1.4 MB) in 1.36s (largest was `encoding_rs` at 1.4 MB)
<font color="#2AA1B3"><b>    Blocking</b></font> waiting for file lock on package cache
<font color="#26A269"><b>   Compiling</b></font> autocfg v1.2.0
<font color="#26A269"><b>   Compiling</b></font> libm v0.2.8
<font color="#26A269"><b>   Compiling</b></font> bytemuck v1.15.0
<font color="#26A269"><b>   Compiling</b></font> cfg-if v1.0.0
<font color="#26A269"><b>   Compiling</b></font> proc-macro2 v1.0.79
<font color="#26A269"><b>   Compiling</b></font> semver v1.0.22
<font color="#26A269"><b>   Compiling</b></font> unicode-ident v1.0.12
<font color="#26A269"><b>   Compiling</b></font> bitflags v1.3.2
<font color="#26A269"><b>   Compiling</b></font> wasi v0.11.0+wasi-snapshot-preview1
<font color="#26A269"><b>   Compiling</b></font> arrayvec v0.7.4
<font color="#26A269"><b>   Compiling</b></font> lazy_static v1.4.0
<font color="#26A269"><b>   Compiling</b></font> log v0.4.21
<font color="#26A269"><b>   Compiling</b></font> getrandom v0.2.14
<font color="#26A269"><b>   Compiling</b></font> paste v1.0.14
<font color="#26A269"><b>   Compiling</b></font> safe_arch v0.7.1
<font color="#26A269"><b>   Compiling</b></font> rand_core v0.6.4
<font color="#26A269"><b>   Compiling</b></font> symphonia-core v0.5.4
<font color="#26A269"><b>   Compiling</b></font> ppv-lite86 v0.2.17
<font color="#26A269"><b>   Compiling</b></font> num-traits v0.2.18
<font color="#26A269"><b>   Compiling</b></font> num-bigint v0.4.4
<font color="#26A269"><b>   Compiling</b></font> num-rational v0.4.1
<font color="#26A269"><b>   Compiling</b></font> matrixmultiply v0.3.8
<font color="#26A269"><b>   Compiling</b></font> typenum v1.17.0
<font color="#26A269"><b>   Compiling</b></font> rand_chacha v0.3.1
<font color="#26A269"><b>   Compiling</b></font> quote v1.0.35
<font color="#26A269"><b>   Compiling</b></font> syn v2.0.58
<font color="#26A269"><b>   Compiling</b></font> rustc_version v0.4.0
<font color="#26A269"><b>   Compiling</b></font> wide v0.7.15
<font color="#26A269"><b>   Compiling</b></font> ttf-parser v0.20.0
<font color="#26A269"><b>   Compiling</b></font> memchr v2.7.2
<font color="#26A269"><b>   Compiling</b></font> rawpointer v0.2.1
<font color="#26A269"><b>   Compiling</b></font> zune-core v0.4.12
<font color="#26A269"><b>   Compiling</b></font> num-integer v0.1.46
<font color="#26A269"><b>   Compiling</b></font> num-complex v0.4.5
<font color="#26A269"><b>   Compiling</b></font> approx v0.5.1
<font color="#26A269"><b>   Compiling</b></font> thiserror v1.0.58
<font color="#26A269"><b>   Compiling</b></font> ab_glyph_rasterizer v0.1.8
<font color="#26A269"><b>   Compiling</b></font> num-iter v0.1.44
<font color="#26A269"><b>   Compiling</b></font> zune-jpeg v0.4.11
<font color="#26A269"><b>   Compiling</b></font> aho-corasick v1.1.3
<font color="#26A269"><b>   Compiling</b></font> owned_ttf_parser v0.20.0
<font color="#26A269"><b>   Compiling</b></font> simba v0.8.1
<font color="#26A269"><b>   Compiling</b></font> flatbuffers v23.5.26
<font color="#26A269"><b>   Compiling</b></font> thiserror-impl v1.0.58
<font color="#26A269"><b>   Compiling</b></font> rand v0.8.5
<font color="#26A269"><b>   Compiling</b></font> encoding_rs v0.8.33
<font color="#26A269"><b>   Compiling</b></font> regex-syntax v0.8.3
<font color="#26A269"><b>   Compiling</b></font> ttf-parser v0.15.2
<font color="#26A269"><b>   Compiling</b></font> byteorder v1.5.0
<font color="#26A269"><b>   Compiling</b></font> custom_derive v0.1.7
<font color="#26A269"><b>   Compiling</b></font> either v1.10.0
<font color="#26A269"><b>   Compiling</b></font> itertools v0.12.1
<font color="#26A269"><b>   Compiling</b></font> owned_ttf_parser v0.15.2
<font color="#26A269"><b>   Compiling</b></font> regex-automata v0.4.6
<font color="#26A269"><b>   Compiling</b></font> conv v0.3.3
<font color="#26A269"><b>   Compiling</b></font> image v0.25.1
<font color="#26A269"><b>   Compiling</b></font> symphonia-metadata v0.5.4
<font color="#26A269"><b>   Compiling</b></font> rand_distr v0.4.3
<font color="#26A269"><b>   Compiling</b></font> ab_glyph v0.2.24
<font color="#26A269"><b>   Compiling</b></font> num v0.4.1
<font color="#26A269"><b>   Compiling</b></font> mediapipe-rs v0.1.0-dev (/home/magee/mj/study/rust_wasm/AI_inference/mediapipe solutions/demo-object-detection/mediapipe-rs)
<font color="#26A269"><b>   Compiling</b></font> extended v0.1.0
<font color="#26A269"><b>   Compiling</b></font> symphonia-format-riff v0.5.4
<font color="#26A269"><b>   Compiling</b></font> nalgebra v0.32.5
<font color="#26A269"><b>   Compiling</b></font> regex v1.10.4
<font color="#26A269"><b>   Compiling</b></font> wasi-nn v0.6.0
<font color="#26A269"><b>   Compiling</b></font> rusttype v0.9.3
<font color="#26A269"><b>   Compiling</b></font> symphonia-codec-pcm v0.5.4
<font color="#26A269"><b>   Compiling</b></font> symphonia v0.5.4
<font color="#26A269"><b>   Compiling</b></font> imageproc v0.24.0
<font color="#F66151"><b>error[E0277]</b></font><b>: `Rc&lt;ttf_parser::Face&lt;&apos;static&gt;&gt;` cannot be shared between threads safely</b>
  <font color="#2A7BDE"><b>--&gt; </b></font>src/postprocess/utils/vision/default_font/mod.rs:10:1
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>10</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>/</b></font> lazy_static::lazy_static! {
<font color="#2A7BDE"><b>11</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font>     static ref DEFAULT_FONT: Font&lt;&apos;static&gt; = Font::try_from_bytes(DEFAULT_FONT_BYTES).unwrap();
<font color="#2A7BDE"><b>12</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font>     //static ref DEFAULT_FONT = FontRef::try_from_slice(DEFAULT_FONT_BYTES).unwrap();
<font color="#2A7BDE"><b>13</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font> }
   <font color="#2A7BDE"><b>| </b></font><font color="#F66151"><b>|_^</b></font> <font color="#F66151"><b>`Rc&lt;ttf_parser::Face&lt;&apos;static&gt;&gt;` cannot be shared between threads safely</b></font>
   <font color="#2A7BDE"><b>|</b></font>
   <font color="#2A7BDE"><b>= </b></font><b>help</b>: within `Font&lt;&apos;static&gt;`, the trait `Sync` is not implemented for `Rc&lt;ttf_parser::Face&lt;&apos;static&gt;&gt;`, which is required by `Font&lt;&apos;static&gt;: Sync`
<font color="#33DA7A"><b>note</b></font>: required because it appears within the type `Font&lt;&apos;static&gt;`
  <font color="#2A7BDE"><b>--&gt; </b></font>/home/magee/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rusttype-0.9.3/src/font.rs:31:10
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>31</b></font> <font color="#2A7BDE"><b>|</b></font> pub enum Font&lt;&apos;a&gt; {
   <font color="#2A7BDE"><b>| </b></font>         <font color="#33DA7A"><b>^^^^</b></font>
<font color="#33DA7A"><b>note</b></font>: required by a bound in `Lazy`
  <font color="#2A7BDE"><b>--&gt; </b></font>/home/magee/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/inline_lazy.rs:19:20
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>19</b></font> <font color="#2A7BDE"><b>|</b></font> pub struct Lazy&lt;T: Sync&gt;(Cell&lt;Option&lt;T&gt;&gt;, Once);
   <font color="#2A7BDE"><b>| </b></font>                   <font color="#33DA7A"><b>^^^^</b></font> <font color="#33DA7A"><b>required by this bound in `Lazy`</b></font>
   <font color="#2A7BDE"><b>= </b></font><b>note</b>: this error originates in the macro `__lazy_static_create` which comes from the expansion of the macro `lazy_static::lazy_static` (in Nightly builds, run with -Z macro-backtrace for more info)

<font color="#F66151"><b>error[E0277]</b></font><b>: `Rc&lt;owned_ttf_parser::owned::OwnedFace&gt;` cannot be shared between threads safely</b>
  <font color="#2A7BDE"><b>--&gt; </b></font>src/postprocess/utils/vision/default_font/mod.rs:10:1
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>10</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>/</b></font> lazy_static::lazy_static! {
<font color="#2A7BDE"><b>11</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font>     static ref DEFAULT_FONT: Font&lt;&apos;static&gt; = Font::try_from_bytes(DEFAULT_FONT_BYTES).unwrap();
<font color="#2A7BDE"><b>12</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font>     //static ref DEFAULT_FONT = FontRef::try_from_slice(DEFAULT_FONT_BYTES).unwrap();
<font color="#2A7BDE"><b>13</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font> }
   <font color="#2A7BDE"><b>| </b></font><font color="#F66151"><b>|_^</b></font> <font color="#F66151"><b>`Rc&lt;owned_ttf_parser::owned::OwnedFace&gt;` cannot be shared between threads safely</b></font>
   <font color="#2A7BDE"><b>|</b></font>
   <font color="#2A7BDE"><b>= </b></font><b>help</b>: within `Font&lt;&apos;static&gt;`, the trait `Sync` is not implemented for `Rc&lt;owned_ttf_parser::owned::OwnedFace&gt;`, which is required by `Font&lt;&apos;static&gt;: Sync`
<font color="#33DA7A"><b>note</b></font>: required because it appears within the type `Font&lt;&apos;static&gt;`
  <font color="#2A7BDE"><b>--&gt; </b></font>/home/magee/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rusttype-0.9.3/src/font.rs:31:10
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>31</b></font> <font color="#2A7BDE"><b>|</b></font> pub enum Font&lt;&apos;a&gt; {
   <font color="#2A7BDE"><b>| </b></font>         <font color="#33DA7A"><b>^^^^</b></font>
<font color="#33DA7A"><b>note</b></font>: required by a bound in `Lazy`
  <font color="#2A7BDE"><b>--&gt; </b></font>/home/magee/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/inline_lazy.rs:19:20
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>19</b></font> <font color="#2A7BDE"><b>|</b></font> pub struct Lazy&lt;T: Sync&gt;(Cell&lt;Option&lt;T&gt;&gt;, Once);
   <font color="#2A7BDE"><b>| </b></font>                   <font color="#33DA7A"><b>^^^^</b></font> <font color="#33DA7A"><b>required by this bound in `Lazy`</b></font>
   <font color="#2A7BDE"><b>= </b></font><b>note</b>: this error originates in the macro `__lazy_static_create` which comes from the expansion of the macro `lazy_static::lazy_static` (in Nightly builds, run with -Z macro-backtrace for more info)

<font color="#F66151"><b>error[E0277]</b></font><b>: `Rc&lt;ttf_parser::Face&lt;&apos;static&gt;&gt;` cannot be shared between threads safely</b>
  <font color="#2A7BDE"><b>--&gt; </b></font>src/postprocess/utils/vision/default_font/mod.rs:10:1
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>10</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>/</b></font> lazy_static::lazy_static! {
<font color="#2A7BDE"><b>11</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font>     static ref DEFAULT_FONT: Font&lt;&apos;static&gt; = Font::try_from_bytes(DEFAULT_FONT_BYTES).unwrap();
<font color="#2A7BDE"><b>12</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font>     //static ref DEFAULT_FONT = FontRef::try_from_slice(DEFAULT_FONT_BYTES).unwrap();
<font color="#2A7BDE"><b>13</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font> }
   <font color="#2A7BDE"><b>| </b></font><font color="#F66151"><b>|_^</b></font> <font color="#F66151"><b>`Rc&lt;ttf_parser::Face&lt;&apos;static&gt;&gt;` cannot be shared between threads safely</b></font>
   <font color="#2A7BDE"><b>|</b></font>
   <font color="#2A7BDE"><b>= </b></font><b>help</b>: within `Font&lt;&apos;static&gt;`, the trait `Sync` is not implemented for `Rc&lt;ttf_parser::Face&lt;&apos;static&gt;&gt;`, which is required by `Font&lt;&apos;static&gt;: Sync`
<font color="#33DA7A"><b>note</b></font>: required because it appears within the type `Font&lt;&apos;static&gt;`
  <font color="#2A7BDE"><b>--&gt; </b></font>/home/magee/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rusttype-0.9.3/src/font.rs:31:10
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>31</b></font> <font color="#2A7BDE"><b>|</b></font> pub enum Font&lt;&apos;a&gt; {
   <font color="#2A7BDE"><b>| </b></font>         <font color="#33DA7A"><b>^^^^</b></font>
<font color="#33DA7A"><b>note</b></font>: required by a bound in `Lazy::&lt;T&gt;::INIT`
  <font color="#2A7BDE"><b>--&gt; </b></font>/home/magee/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/inline_lazy.rs:21:9
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>21</b></font> <font color="#2A7BDE"><b>|</b></font> impl&lt;T: Sync&gt; Lazy&lt;T&gt; {
   <font color="#2A7BDE"><b>| </b></font>        <font color="#33DA7A"><b>^^^^</b></font> <font color="#33DA7A"><b>required by this bound in `Lazy::&lt;T&gt;::INIT`</b></font>
<font color="#2A7BDE"><b>22</b></font> <font color="#2A7BDE"><b>|</b></font>     #[allow(deprecated)]
<font color="#2A7BDE"><b>23</b></font> <font color="#2A7BDE"><b>|</b></font>     pub const INIT: Self = Lazy(Cell::new(None), ONCE_INIT);
   <font color="#2A7BDE"><b>| </b></font>              <font color="#2A7BDE"><b>----</b></font> <font color="#2A7BDE"><b>required by a bound in this associated constant</b></font>
   <font color="#2A7BDE"><b>= </b></font><b>note</b>: this error originates in the macro `__lazy_static_create` which comes from the expansion of the macro `lazy_static::lazy_static` (in Nightly builds, run with -Z macro-backtrace for more info)

<font color="#F66151"><b>error[E0277]</b></font><b>: `Rc&lt;owned_ttf_parser::owned::OwnedFace&gt;` cannot be shared between threads safely</b>
  <font color="#2A7BDE"><b>--&gt; </b></font>src/postprocess/utils/vision/default_font/mod.rs:10:1
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>10</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>/</b></font> lazy_static::lazy_static! {
<font color="#2A7BDE"><b>11</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font>     static ref DEFAULT_FONT: Font&lt;&apos;static&gt; = Font::try_from_bytes(DEFAULT_FONT_BYTES).unwrap();
<font color="#2A7BDE"><b>12</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font>     //static ref DEFAULT_FONT = FontRef::try_from_slice(DEFAULT_FONT_BYTES).unwrap();
<font color="#2A7BDE"><b>13</b></font> <font color="#2A7BDE"><b>|</b></font> <font color="#F66151"><b>|</b></font> }
   <font color="#2A7BDE"><b>| </b></font><font color="#F66151"><b>|_^</b></font> <font color="#F66151"><b>`Rc&lt;owned_ttf_parser::owned::OwnedFace&gt;` cannot be shared between threads safely</b></font>
   <font color="#2A7BDE"><b>|</b></font>
   <font color="#2A7BDE"><b>= </b></font><b>help</b>: within `Font&lt;&apos;static&gt;`, the trait `Sync` is not implemented for `Rc&lt;owned_ttf_parser::owned::OwnedFace&gt;`, which is required by `Font&lt;&apos;static&gt;: Sync`
<font color="#33DA7A"><b>note</b></font>: required because it appears within the type `Font&lt;&apos;static&gt;`
  <font color="#2A7BDE"><b>--&gt; </b></font>/home/magee/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rusttype-0.9.3/src/font.rs:31:10
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>31</b></font> <font color="#2A7BDE"><b>|</b></font> pub enum Font&lt;&apos;a&gt; {
   <font color="#2A7BDE"><b>| </b></font>         <font color="#33DA7A"><b>^^^^</b></font>
<font color="#33DA7A"><b>note</b></font>: required by a bound in `Lazy::&lt;T&gt;::INIT`
  <font color="#2A7BDE"><b>--&gt; </b></font>/home/magee/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/inline_lazy.rs:21:9
   <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>21</b></font> <font color="#2A7BDE"><b>|</b></font> impl&lt;T: Sync&gt; Lazy&lt;T&gt; {
   <font color="#2A7BDE"><b>| </b></font>        <font color="#33DA7A"><b>^^^^</b></font> <font color="#33DA7A"><b>required by this bound in `Lazy::&lt;T&gt;::INIT`</b></font>
<font color="#2A7BDE"><b>22</b></font> <font color="#2A7BDE"><b>|</b></font>     #[allow(deprecated)]
<font color="#2A7BDE"><b>23</b></font> <font color="#2A7BDE"><b>|</b></font>     pub const INIT: Self = Lazy(Cell::new(None), ONCE_INIT);
   <font color="#2A7BDE"><b>| </b></font>              <font color="#2A7BDE"><b>----</b></font> <font color="#2A7BDE"><b>required by a bound in this associated constant</b></font>
   <font color="#2A7BDE"><b>= </b></font><b>note</b>: this error originates in the macro `__lazy_static_create` which comes from the expansion of the macro `lazy_static::lazy_static` (in Nightly builds, run with -Z macro-backtrace for more info)

<b>For more information about this error, try `rustc --explain E0277`.</b>
<font color="#C01C28"><b>error</b></font><b>:</b> could not compile `mediapipe-rs` (lib) due to 4 previous errors
<font color="#A2734C"><b>warning</b></font><b>:</b> build failed, waiting for other jobs to finish...
</pre>

**Comment by hydai** [comment]
Hi @yanghaku 
Could you please check this issue?
